# Generated by Django 5.1.6 on 2025-02-17 16:45

import datetime
import django.db.models.expressions
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField(unique=True)),
                ("book", models.IntegerField(unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Available"),
                            (2, "On Loan"),
                            (3, "Lost"),
                            (4, "Damaged"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        db_default=django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.datetime.Now(),
                            "+",
                            models.Value(datetime.timedelta(days=30)),
                        )
                    ),
                ),
                ("insert_date", models.DateField(auto_now_add=True)),
                ("update_date", models.DateField(auto_now=True)),
            ],
        ),
    ]
