# Generated by Django 5.1.5 on 2025-02-19 15:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("insert_date", models.DateField(auto_now_add=True)),
                ("update_date", models.DateField(auto_now=True)),
                ("activate", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("editor", models.CharField(max_length=100)),
                ("insert_date", models.DateField(auto_now_add=True)),
                ("update_date", models.DateField(auto_now=True)),
                ("activate", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=255)),
                ("insert_date", models.DateField(auto_now_add=True)),
                ("update_date", models.DateField(auto_now=True)),
                ("activate", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "isbn",
                    models.CharField(
                        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                        max_length=13,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                ("publication_date", models.DateField()),
                ("qty", models.IntegerField()),
                ("activate", models.BooleanField(default=True)),
                ("insert_date", models.DateField(default=datetime.date(2025, 2, 19))),
                ("update_date", models.DateField()),
                (
                    "author",
                    models.ManyToManyField(
                        help_text="Select one or more author for this book",
                        to="library_app.author",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="Select an editor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.editor",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        help_text="Select one or more genre for this book",
                        to="library_app.genre",
                    ),
                ),
            ],
        ),
    ]
