# Generated by Django 5.1.5 on 2025-02-19 15:56

import library_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0002_author_editor_genre_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="book",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="user",
        ),
        migrations.AddField(
            model_name="loan",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="book_ID",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="user_ID",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="update_date",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="due_date",
            field=models.DateField(default=library_app.models.Loan.auto_due_date),
        ),
    ]
