# Generated by Django 5.1.6 on 2025-02-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_author_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name_author',
            new_name='author',
        ),
    ]
